export {
  AddressInfoForm,
  AvatarInfoForm,
  CheckBoxForm,
  DatePickerInfoForm,
  DefaultInputForm,
  MBITInfoForm,
  PhoneInfoForm,
  TextAreaForm,
  ToolInfoForm,
  DateTimePickerForm,
  EndDateForm,
  ParticipateForm,
  RepeatDayForm,
  DropdownForm,
  SelectForm,
} from './InputForm'
